### PR TITLE
Minor enhancements.

### PR DESCRIPTION
**Pull request by troygeiger**
Hello,
Here are some minor changes I wanted to implement:
- Automatically open solution, when opening repository, if only one .sln file is found in the root.
- Show active repository with bold font.
- Use string resource for new context menu.

Everything else seems to be working really well!

### CODE REVIEW

**Comment by troygeiger** [comment]
Thanks for accepting my pull request. When do you think it will be ready for release?

**Comment by maikebing** [comment]
Publish after the scheduled completion feature "URL opens local code file" and "opens the URL of the current file in the browser"

**Comment by maikebing** [comment]
I have submitted the code, do you have time to help test it?
When you right-click in the Code Editor, then Gitea->master ，the error is reported

 I think there may be a problem with my environment. The problem is similar to https://github.com/libgit2/libgit2sharp/issues/1588.

**Comment by troygeiger** [comment]
After some testing, I was able to get past the Unable to load DLL after updating the LibGit2Sharp.NativeBinaries on all of the projects. Now I am receiving a error while MenuItem_BeforeQueryStatus is calling git.GetGiteaTargetPath. 
In GitAnalysis.cs Line 59, this is the error:
'repository.Head.FriendlyName' threw an exception of type 'System.AccessViolationException'
I haven't found the cause of it.

**Comment by maikebing** [comment]
It's done, it's been released.

**Pull request merged**
